# permissions for end users to edit helmrepos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmrepo-editor-role
rules:
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmrepos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmrepos/status
  verbs:
  - get
