# permissions for end users to edit helmoperations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmoperation-editor-role
rules:
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmoperations/status
  verbs:
  - get
