# permissions for end users to view helmapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmapplication-viewer-role
rules:
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmapplications/status
  verbs:
  - get
