# permissions for end users to view helmoperations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helmoperation-viewer-role
rules:
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmoperations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmoperations/status
  verbs:
  - get
