
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmoperations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmoperations/finalizers
  verbs:
  - update
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmoperations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmrepos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmrepos/finalizers
  verbs:
  - update
- apiGroups:
  - helmops.shijunlee.net
  resources:
  - helmrepos/status
  verbs:
  - get
  - patch
  - update
