apiVersion: helmops.shijunlee.net/v1alpha1
kind: HelmOperation
metadata:
  name: log-test
spec:
  # Add fields here
  values: {}
  autoUpdate: false
  chartRepoName: tpaas-itg
  chartVersion: 0.1.0
  chartName: log-test
  create:
    description: "create a log test"
    skipCRDs: false
    timeout: 300
    noHook: false
    generateName: false
    createNamespace: false
    disableOpenAPIValidation: false
    isUpgrade: false
    waitForJobs: false
    replace: false
    wait: false
  upgrade: 
    install: false
    devel: false
    skipCRDs: false
    timeout: 300
    wait: false
    disableHooks: false
    force: false
    resetValues: false
    reuseValues: true
    recreate: false
    maxHistory: 10
    atomic: true
    cleanupOnFail: false
    description: "upgrade a log test"
    disableOpenAPIValidation: false
    waitForJobs: false
    upgradeCRDs: false
  uninstall: 
    disableHooks: false
    keepHistory: false
    timeout: 300
    description: "delete a log test"
    doNotDeleteRelease: false
